"""Apex Sovereign - control-plane route registration runtime helpers."""

from typing import Any


def register_control_plane_routes(
    *,
    app: Any,
    authz_engine: Any,
    get_identity: Any,
    get_redis_client: Any,
    threat_intel_store_factory: Any,
    create_unsigned_ledger_entry: Any,
    ledger_backpressure_error_cls: Any,
    control_plane_payloads: Any,
    policy_records: Any,
    region: str,
    chain_id: str,
    control_plane_reads: Any,
    read_signing_audit_stream: Any,
    get_apex_env: Any,
    sign_audit_enabled: bool,
    sign_audit_stream_key: str,
    sign_audit_ttl_seconds: int,
    threat_intel_versions_key: str,
    dlp_semantic_store_factory: Any,
    policy_store_factory: Any,
    seed_policy_for_group: Any,
    no_content_retention_enabled: Any,
    policy_retention_seconds: Any,
    dlp_semantic_enabled: bool,
    embedding_model: str,
    dlp_semantic_max_exemplars: int,
    load_signer_for_worker: Any,
    signer_health: Any,
    two_person_policy: bool,
    policy_version: str,
    policy_record_cls: Any,
    policy_governance: Any,
    policy_views: Any,
    model_allowlist: Any,
    external_model_map: Any,
    model_catalog: Any,
    fips_mode: bool,
    validate_retention_policy_or_raise: Any,
    effective_retention_seconds: Any,
    compliance_mode: bool,
    compliance_require_ttls: bool,
    max_session_prompts_ttl_seconds: int,
    max_adversarial_corpus_ttl_seconds: int,
    max_content_store_ttl_seconds: int,
    best_effort_governance_ledger_event: Any,
    runtime_snapshot: Any,
    is_sensitive_env_key: Any,
    redact_env_value: Any,
    tenant_store_factory: Any,
    drift_engine_factory: Any,
    drift_backend: Any,
    vector_backend_cls: Any,
    redis_bow_backend_cls: Any,
    get_rtbf_proof_payload: Any,
    record_metrics_for_audit: Any,
    utc_now_z: Any,
    dlp_items_key: str,
    dlp_meta_key: str,
    rtbf_s3_allow: bool,
    rtbf_s3_bucket: str,
    ledger_s3_bucket: str,
    ledger_checkpoint_bucket: str,
    rtbf_proof_cache_ttl_seconds: int,
    ledger_verify_helpers: Any,
    decode_single_json_skip_invalid: Any,
    decode_optional_json_object_or_default: Any,
    decode_required_json_object: Any,
    compute_entry_hash: Any,
    dashboard_routes: Any,
    egress_check_url: Any,
    compile_egress_allowlist_patterns: Any,
    block_ip_literals: bool,
    allowlist_regex: str,
    audit_blocks: bool,
    dashboard_views: Any,
    retention_payload_builder: Any,
    dlp_embedding_model: str,
    dlp_max_exemplars: int,
    ledger_audit_routes: Any,
    ledger_verify_routes: Any,
    read_raw_ledger_entry: Any,
    extract_entry_hash_leaves: Any,
    compute_merkle_root_hex: Any,
    compute_merkle_inclusion_proof_hex: Any,
    get_signer_public_key_b64: Any,
    verify_scan_limit: int,
    anchor_search_limit: int,
    policy_routes: Any,
    env_config_routes: Any,
    admin_misc_routes: Any,
    rtbf_routes: Any,
    admin_security_routes: Any,
    metrics_hour_key: str,
    metrics_total_key: str,
    metrics_blocked_key: str,
    metrics_highrisk_key: str,
    metrics_axis_hash_key: str,
    max_unsigned_queue: int,
    get_unsigned_backlog_status: Any,
) -> None:
    admin_security_routes.register_admin_security_routes(
        app,
        authz_engine=authz_engine,
        get_identity=get_identity,
        get_redis_client=get_redis_client,
        threat_intel_store_factory=threat_intel_store_factory,
        create_unsigned_ledger_entry=create_unsigned_ledger_entry,
        ledger_backpressure_error_cls=ledger_backpressure_error_cls,
        control_plane_payloads=control_plane_payloads,
        policy_records=policy_records,
        region=region,
        chain_id=chain_id,
        control_plane_reads=control_plane_reads,
        read_signing_audit_stream=read_signing_audit_stream,
        get_apex_env=get_apex_env,
        sign_audit_enabled=sign_audit_enabled,
        sign_audit_stream_key=sign_audit_stream_key,
        sign_audit_ttl_seconds=sign_audit_ttl_seconds,
        threat_intel_versions_key=threat_intel_versions_key,
        dlp_semantic_store_factory=dlp_semantic_store_factory,
        policy_store_factory=policy_store_factory,
        seed_policy_for_group=seed_policy_for_group,
        no_content_retention_enabled=no_content_retention_enabled,
        policy_retention_seconds=policy_retention_seconds,
        dlp_semantic_enabled=dlp_semantic_enabled,
        embedding_model=embedding_model,
        dlp_semantic_max_exemplars=dlp_semantic_max_exemplars,
        load_signer_for_worker=load_signer_for_worker,
        signer_health=signer_health,
    )

    policy_routes.register_policy_routes(
        app,
        authz_engine=authz_engine,
        get_identity=get_identity,
        get_redis_client=get_redis_client,
        two_person_policy=two_person_policy,
        policy_version=policy_version,
        seed_policy_for_group=seed_policy_for_group,
        policy_store_factory=policy_store_factory,
        policy_record_cls=policy_record_cls,
        policy_records=policy_records,
        policy_governance=policy_governance,
        policy_views=policy_views,
        control_plane_reads=control_plane_reads,
        control_plane_payloads=control_plane_payloads,
        model_allowlist=model_allowlist,
        external_model_map=external_model_map,
        model_catalog=model_catalog,
        validate_retention_policy_or_raise=validate_retention_policy_or_raise,
        effective_retention_seconds=effective_retention_seconds,
        compliance_mode=compliance_mode,
        compliance_require_ttls=compliance_require_ttls,
        max_session_prompts_ttl_seconds=max_session_prompts_ttl_seconds,
        max_adversarial_corpus_ttl_seconds=max_adversarial_corpus_ttl_seconds,
        max_content_store_ttl_seconds=max_content_store_ttl_seconds,
        best_effort_governance_ledger_event=best_effort_governance_ledger_event,
    )

    env_config_routes.register_env_config_routes(
        app,
        authz_engine=authz_engine,
        get_identity=get_identity,
        get_redis_client=get_redis_client,
        get_apex_env=get_apex_env,
        runtime_snapshot=runtime_snapshot,
        is_sensitive_env_key=is_sensitive_env_key,
        redact_env_value=redact_env_value,
        best_effort_governance_ledger_event=best_effort_governance_ledger_event,
    )

    admin_misc_routes.register_admin_misc_routes(
        app,
        authz_engine=authz_engine,
        get_identity=get_identity,
        get_redis_client=get_redis_client,
        tenant_store_factory=tenant_store_factory,
        control_plane_reads=control_plane_reads,
        dlp_semantic_store_factory=dlp_semantic_store_factory,
        dlp_semantic_enabled=dlp_semantic_enabled,
        embedding_model=embedding_model,
        dlp_semantic_max_exemplars=dlp_semantic_max_exemplars,
        drift_engine_factory=drift_engine_factory,
        drift_backend=drift_backend,
        vector_backend_cls=vector_backend_cls,
        redis_bow_backend_cls=redis_bow_backend_cls,
    )

    rtbf_routes.register_rtbf_routes(
        app,
        authz_engine=authz_engine,
        get_identity=get_identity,
        get_redis_client=get_redis_client,
        get_rtbf_proof_payload=get_rtbf_proof_payload,
        create_unsigned_ledger_entry=create_unsigned_ledger_entry,
        record_metrics_for_audit=record_metrics_for_audit,
        ledger_backpressure_error_cls=ledger_backpressure_error_cls,
        utc_now_z=utc_now_z,
        policy_version=policy_version,
        region=region,
        chain_id=chain_id,
        drift_engine_factory=drift_engine_factory,
        drift_backend=drift_backend,
        vector_backend_cls=vector_backend_cls,
        redis_bow_backend_cls=redis_bow_backend_cls,
        dlp_store_factory=dlp_semantic_store_factory,
        dlp_items_key=dlp_items_key,
        dlp_meta_key=dlp_meta_key,
        rtbf_s3_allow=rtbf_s3_allow,
        rtbf_s3_bucket=rtbf_s3_bucket,
        ledger_s3_bucket=ledger_s3_bucket,
        ledger_checkpoint_bucket=ledger_checkpoint_bucket,
        rtbf_proof_cache_ttl_seconds=rtbf_proof_cache_ttl_seconds,
    )

    ledger_verify_helpers.configure_ledger_verify_helpers(
        get_redis_client_fn=get_redis_client,
        decode_single_json_skip_invalid_fn=decode_single_json_skip_invalid,
        decode_optional_json_object_or_default_fn=decode_optional_json_object_or_default,
        decode_required_json_object_fn=decode_required_json_object,
        compute_entry_hash_fn=compute_entry_hash,
        apex_region=region,
        apex_chain_id=chain_id,
    )
    verify_ledger_chain_for_api = ledger_verify_helpers.verify_ledger_chain_for_api

    dashboard_routes.register_dashboard_routes(
        app,
        authz_engine=authz_engine,
        get_identity=get_identity,
        get_redis_client=get_redis_client,
        get_apex_env=get_apex_env,
        get_unsigned_backlog_status=get_unsigned_backlog_status,
        ledger_backlog_state_label=control_plane_payloads.ledger_backlog_state_label,
        fips_mode=fips_mode,
        policy_version=policy_version,
        region=region,
        chain_id=chain_id,
        egress_check_url=egress_check_url,
        compile_egress_allowlist_patterns=compile_egress_allowlist_patterns,
        utc_now_z=utc_now_z,
        block_ip_literals=block_ip_literals,
        allowlist_regex=allowlist_regex,
        audit_blocks=audit_blocks,
        model_catalog=model_catalog,
        dashboard_views=dashboard_views,
        control_plane_reads=control_plane_reads,
        policy_views=policy_views,
        max_unsigned_queue=max_unsigned_queue,
        decode_single_json_skip_invalid=decode_single_json_skip_invalid,
        compute_entry_hash=compute_entry_hash,
        metrics_hour_key=metrics_hour_key,
        metrics_total_key=metrics_total_key,
        metrics_blocked_key=metrics_blocked_key,
        metrics_highrisk_key=metrics_highrisk_key,
        metrics_axis_hash_key=metrics_axis_hash_key,
        verify_ledger_chain_for_api=verify_ledger_chain_for_api,
        seed_policy_for_group=seed_policy_for_group,
        effective_retention_seconds=effective_retention_seconds,
        retention_payload_builder=retention_payload_builder,
        compliance_mode=compliance_mode,
        compliance_require_ttls=compliance_require_ttls,
        max_session_prompts_ttl_seconds=max_session_prompts_ttl_seconds,
        max_adversarial_corpus_ttl_seconds=max_adversarial_corpus_ttl_seconds,
        max_content_store_ttl_seconds=max_content_store_ttl_seconds,
        dlp_semantic_store_factory=dlp_semantic_store_factory,
        dlp_semantic_enabled=dlp_semantic_enabled,
        dlp_embedding_model=dlp_embedding_model,
        dlp_max_exemplars=dlp_max_exemplars,
        policy_store_factory=policy_store_factory,
    )

    ledger_audit_routes.register_ledger_audit_routes(
        app,
        authz_engine=authz_engine,
        get_identity=get_identity,
        get_redis_client=get_redis_client,
        verify_ledger_chain_for_api=verify_ledger_chain_for_api,
        region=region,
        chain_id=chain_id,
        policy_version=policy_version,
        utc_now_z=utc_now_z,
        decode_single_json_skip_invalid=decode_single_json_skip_invalid,
    )

    ledger_verify_routes.register_ledger_verify_routes(
        app,
        authz_engine=authz_engine,
        get_identity=get_identity,
        get_redis_client=get_redis_client,
        read_raw_ledger_entry=read_raw_ledger_entry,
        decode_single_json_skip_invalid=decode_single_json_skip_invalid,
        extract_entry_hash_leaves=extract_entry_hash_leaves,
        compute_entry_hash=compute_entry_hash,
        compute_merkle_root_hex=compute_merkle_root_hex,
        compute_merkle_inclusion_proof_hex=compute_merkle_inclusion_proof_hex,
        get_signer_public_key_b64=get_signer_public_key_b64,
        verify_scan_limit=verify_scan_limit,
        anchor_search_limit=anchor_search_limit,
    )
